# Copyright 2021 The golang.design Initiative Authors.
# All rights reserved. Use of this source code is governed
# by a MIT license that can be found in the LICENSE file.

version: "3"
services:
  redir:
    container_name: redir
    restart: always
    image: redir:latest
    environment:
      REDIR_CONF: ./data/redirconf.yml
    ports:
      - "9123:8080"
    depends_on:
      - mysql
    deploy:
      replicas: 1
    networks:
      - traefik_proxy
  mysql:
    container_name: redirdb
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ../data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: redir
    restart: always
    networks:
      - traefik_proxy
networks:
  traefik_proxy:
    external: true
