# Copyright 2021 The golang.design Initiative Authors.
# All rights reserved. Use of this source code is governed
# by a MIT license that can be found in the LICENSE file.

version: "3"
services:
  redir:
    container_name: golang-design/redir
    restart: always
    image: golang-design/redir:latest
    environment:
      REDIR_CONF: ./data/redirconf.yml
    ports:
      - "80:80"
    depends_on:
      - mysql
    deploy:
      replicas: 1
    networks:
      - traefik_proxy
  mysql:
    container_name: golang-design/redirdb
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ../data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: redir
    cap_add:
      - SYS_NICE
    restart: always
    networks:
      - traefik_proxy
networks:
  traefik_proxy:
    external: true
