# Copyright 2021 The golang.design Initiative Authors.
# All rights reserved. Use of this source code is governed
# by a MIT license that can be found in the LICENSE file.

version: "3"
services:
  golangdesign-redir:
    container_name: golangdesign-redir
    restart: always
    image: golangdesign-redir:latest
    environment:
      REDIR_CONF: ./data/redirconf.yml
    depends_on:
      - golangdesign-mysql
    deploy:
      replicas: 1
    networks:
      - traefik_proxy
  golangdesign-mysql:
    container_name: golangdesign-redirdb
    image: mysql:latest
    volumes:
      - ../data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: redir
    cap_add:
      - SYS_NICE
    restart: always
    networks:
      - traefik_proxy
networks:
  traefik_proxy:
    external: true
